sonar.projectKey=cincytm_student-marks-app
<<<<<<< HEAD
sonar.projectName=student-marks-app
=======
sonar.organization=cincytm
sonar.projectName=Traica Student Marks
>>>>>>> d653e8f (sonar property file updated with projectkey)
sonar.sources=.
sonar.exclusions=.git/**,.github/**,__pycache__/**
sonar.python.version=3.12
